update:
    canaries: 0
    max_in_flight: 3

jobs:
    - instances: 1
      <<: (( merge ))
      networks:
          - name: test-network
            static_ips:
                - 10.244.0.3

networks:
    - name: test-network
      subnets:
          - gateway: 10.244.0.1
            static:
                - 10.244.0.3
