compilation:
  cloud_properties:
    name: random
  network: test-network
  reuse_compilation_vms: true
  workers: 1
director_uuid: <%= `bosh status --uuid` %>
jobs:
- instances: 1
  name: Shared-VMR
  networks:
  - name: test-network
    static_ips:
    - 10.244.0.3
  persistent_disk: 20480
  properties:
    admin_password: admin
    admin_user: admin
    application_access_auth_scheme: vmr_internal
    broker_hostname: solace-messaging.local.pcfdev.io
    broker_password: solacedemo
    broker_user: solacedemo
    broker_validate_cert_disabled: false
    cert_pem: |
      -----BEGIN CERTIFICATE-----
      MIIDnzCCAoegAwIBAgIJAKEsd5V3+exFMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
      BAYTAkNBMQswCQYDVQQIDAJPTjEPMA0GA1UEBwwGS2FuYXRhMQ8wDQYDVQQKDAZT
      b2xhY2UxGTAXBgNVBAsMEENsb3VkSW50ZWdyYXRpb24xDDAKBgNVBAMMA1BvQzAg
      Fw0xNjEwMjcxNzA3MDRaGA8yMTE2MTAwMzE3MDcwNFowZTELMAkGA1UEBhMCQ0Ex
      CzAJBgNVBAgMAk9OMQ8wDQYDVQQHDAZLYW5hdGExDzANBgNVBAoMBlNvbGFjZTEZ
      MBcGA1UECwwQQ2xvdWRJbnRlZ3JhdGlvbjEMMAoGA1UEAwwDUG9DMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4U3oyVABZuRGJoMzUX4y+KA6ImOucCQQ
      pLK4X3ZQj4cBf3OGp0Z8eNePgHua2LId7qs4K3R2qWxQy3Mgl23FxO+XKzaEpCP+
      RjRJAuN51rbrw5eqSbuNuOFyx6f8VWvxQK44EqqqhDMDPai+RwPZpVvEQ+kR7HTm
      Krfp/goetgb94DmMqEJmBHvKWHIJZFC+ulyriX874X0ZIU3+w+3A1YDbv17SKCnU
      /Oe8OJjMYJWdUEYCIaxWHzqbiXg5JluiEKx/gJNIJvhtry+kJMHCHR3lPAsG9EWP
      UzvrjpkyUXbnnv+xDWFInEeuncpend5dMZlXhx+BXyptRoGjkSNTAQIDAQABo1Aw
      TjAdBgNVHQ4EFgQUl58rrahDoyB48RKuOPzwggwdm40wHwYDVR0jBBgwFoAUl58r
      rahDoyB48RKuOPzwggwdm40wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAFsjDBYpiCNz462duzQdf5ZWXlDfcQ3BDuJe4OD+GlS1abOrwyyhxIcPmiewx
      mV6jxfPWAcgr+4RuZ8bpschbKMdOLaBVrt5hMsnFXP32EmDIdZGygUy5ndlvEdtd
      3J/Ct6S/BzhOiJ09DEzaLS4cg0AXIylCnF+gjglxfrn68ci+/dYpQ2IXqxrWpkpc
      5I3CyDMVn5SAHw4WiVol3ZsmnL1IUsBT1NBSXFaCPL+ys5FRjkZbr7uygBaKPu7r
      q8cMA/GaUHCCyf4F0DQcOs8HSmNDYVHkgsP1HKUra2dWjZcXwRkzAuoLJgspG1GK
      3PVkdvOXQ9ROEMS+OQw0ubc0mQ==
      -----END CERTIFICATE-----
    cf_api_host: api.local.pcfdev.io
    cf_client_id: solace_router
    cf_client_secret: '1234'
    cf_organization: solace
    cf_space: solace-messaging
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest-evaluation

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=admin
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    heartbeat_rate: 15000
    ldap_config: disabled
    management_access_auth_scheme: vmr_internal
    pool_name: Shared-VMR
    private_key_pem: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA4U3oyVABZuRGJoMzUX4y+KA6ImOucCQQpLK4X3ZQj4cBf3OG
      p0Z8eNePgHua2LId7qs4K3R2qWxQy3Mgl23FxO+XKzaEpCP+RjRJAuN51rbrw5eq
      SbuNuOFyx6f8VWvxQK44EqqqhDMDPai+RwPZpVvEQ+kR7HTmKrfp/goetgb94DmM
      qEJmBHvKWHIJZFC+ulyriX874X0ZIU3+w+3A1YDbv17SKCnU/Oe8OJjMYJWdUEYC
      IaxWHzqbiXg5JluiEKx/gJNIJvhtry+kJMHCHR3lPAsG9EWPUzvrjpkyUXbnnv+x
      DWFInEeuncpend5dMZlXhx+BXyptRoGjkSNTAQIDAQABAoIBACOGw3Qq922gBSfB
      fHAXNDZcHY6apUDtjupJfCUhZOac5TGRp+Psi2gKpYge9XXB8FJYEU1Y2fUxLTRH
      fRYjqxG4rd+UgynWuxua1wBrmiSvR1HaMnHZ7yj987lj1bgqgyotzo2y95xM5u/s
      EcTk6IbYh4Ql1juw2zJVOcJjGiCdgdvgAcIvjSRT+sbBL4biw4BRajsX8t+xD73f
      jOfK6RhroZgRgtYMYNsG4gtPoGErYyqNdsOccr81VDpo2HEcOxk1ymy/bea6hEBd
      m3gNA/P23GUxycRcXd4Ki9GfW/XdnHDoGzLVonEJa7xz6uSuw6PhlxVH4+il7PJk
      hDzsJqECgYEA9fak4D+0G7mEKDAec052etqPcjzZsPYUWdj2SLeVD/mF6IJDW+KI
      efCxbzW53gBR91ugmwPxQ4Ti9CBpRNZlKcAPFEU7/S2Njfdc+i/QuQoZQW5Q1FHT
      M70z9WHQFdmWy0D45gndAt9l93ZRRhn32oEsY/OjS6J69ghGOT/ELJ0CgYEA6n91
      UgiBOhg0i/FubstUVbu1xn2XxRgzGpI7ZsrNfxU8jDEwZa9twbhWrUXQhWtq7eWR
      mgWfK3usCxoOiXHJFNeN0jkQxiPErNAz4CrvDbUPboqKHXmeP8f2YGVJl5t1oW7P
      DVTZaLM5Ss1PMlzqtr7DYkm84u8HBa15biWQaLUCgYEAmmWIG+iBM8IhjmSeSL1h
      LD9UOl6uPCJMphXGi+EJpix4/Xn/tIcgKoOHrgqosQ28ZizTRVuVMFATczGBQx/e
      AvY3wP6w6H2W1R4I9FfdironHmaUQKNYk6raGdebmouq183iL+zTGoGHbW6NGBcm
      +beKWPfQcqL80sJg6oD3sRUCgYEAovjAJaoJfcGSy2uYj2G6k/boBzIEB5Og+KeG
      pxLtLJQqx1fsRc9dHVQq0TODDyavYvS4c23SyFqkH/cVAUrWMCj6xI6qbLoxFtWA
      KBxOlZ0vQ2j/Qiri43rqbOYX9kixwOcM+Tvt+QkOGUGE+ACBk04S5j1PC/yJSdXd
      XcK3kT0CgYEAzle+WKkSCsQPMRcP+pWPBK4YGs/pi3fLYlNFN8dCZctLCVXIgXao
      1CzB8vsEva40zy06xHaqbNNpnH0zI0dcsnRFWUqNilZnEYDYjVb0G8oEcNY9AEXm
      P5Z/XHQfurMSM19OUK5EQrSvb7TZKcxV2m3ZBMXg7ccUjh+ZcR3X7rM=
      -----END RSA PRIVATE KEY-----
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: 7000
    syslog_config: disabled
    system_domain: local.pcfdev.io
    tcp_routes_config: enabled
    tls_config: enabled
    vmr_agent_port: 18080
  resource_pool: common-resource-pool
  templates:
  - name: docker
    release: docker
  - name: prepare_vmr
    release: solace-vmr
  - name: containers
    release: solace-vmr
  - name: vmr_agent
    release: solace-vmr
- instances: 1
  name: Community-VMR
  networks:
  - name: test-network
    static_ips:
    - 10.244.0.4
  persistent_disk: 20480
  properties:
    admin_password: admin
    admin_user: admin
    application_access_auth_scheme: vmr_internal
    broker_hostname: solace-messaging.local.pcfdev.io
    broker_password: solacedemo
    broker_user: solacedemo
    broker_validate_cert_disabled: false
    cert_pem: |
      -----BEGIN CERTIFICATE-----
      MIIDnzCCAoegAwIBAgIJAKEsd5V3+exFMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
      BAYTAkNBMQswCQYDVQQIDAJPTjEPMA0GA1UEBwwGS2FuYXRhMQ8wDQYDVQQKDAZT
      b2xhY2UxGTAXBgNVBAsMEENsb3VkSW50ZWdyYXRpb24xDDAKBgNVBAMMA1BvQzAg
      Fw0xNjEwMjcxNzA3MDRaGA8yMTE2MTAwMzE3MDcwNFowZTELMAkGA1UEBhMCQ0Ex
      CzAJBgNVBAgMAk9OMQ8wDQYDVQQHDAZLYW5hdGExDzANBgNVBAoMBlNvbGFjZTEZ
      MBcGA1UECwwQQ2xvdWRJbnRlZ3JhdGlvbjEMMAoGA1UEAwwDUG9DMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4U3oyVABZuRGJoMzUX4y+KA6ImOucCQQ
      pLK4X3ZQj4cBf3OGp0Z8eNePgHua2LId7qs4K3R2qWxQy3Mgl23FxO+XKzaEpCP+
      RjRJAuN51rbrw5eqSbuNuOFyx6f8VWvxQK44EqqqhDMDPai+RwPZpVvEQ+kR7HTm
      Krfp/goetgb94DmMqEJmBHvKWHIJZFC+ulyriX874X0ZIU3+w+3A1YDbv17SKCnU
      /Oe8OJjMYJWdUEYCIaxWHzqbiXg5JluiEKx/gJNIJvhtry+kJMHCHR3lPAsG9EWP
      UzvrjpkyUXbnnv+xDWFInEeuncpend5dMZlXhx+BXyptRoGjkSNTAQIDAQABo1Aw
      TjAdBgNVHQ4EFgQUl58rrahDoyB48RKuOPzwggwdm40wHwYDVR0jBBgwFoAUl58r
      rahDoyB48RKuOPzwggwdm40wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAFsjDBYpiCNz462duzQdf5ZWXlDfcQ3BDuJe4OD+GlS1abOrwyyhxIcPmiewx
      mV6jxfPWAcgr+4RuZ8bpschbKMdOLaBVrt5hMsnFXP32EmDIdZGygUy5ndlvEdtd
      3J/Ct6S/BzhOiJ09DEzaLS4cg0AXIylCnF+gjglxfrn68ci+/dYpQ2IXqxrWpkpc
      5I3CyDMVn5SAHw4WiVol3ZsmnL1IUsBT1NBSXFaCPL+ys5FRjkZbr7uygBaKPu7r
      q8cMA/GaUHCCyf4F0DQcOs8HSmNDYVHkgsP1HKUra2dWjZcXwRkzAuoLJgspG1GK
      3PVkdvOXQ9ROEMS+OQw0ubc0mQ==
      -----END CERTIFICATE-----
    cf_api_host: api.local.pcfdev.io
    cf_client_id: solace_router
    cf_client_secret: '1234'
    cf_organization: solace
    cf_space: solace-messaging
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest-community

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=admin
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    heartbeat_rate: 15000
    ldap_config: disabled
    management_access_auth_scheme: vmr_internal
    pool_name: Community-VMR
    private_key_pem: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA4U3oyVABZuRGJoMzUX4y+KA6ImOucCQQpLK4X3ZQj4cBf3OG
      p0Z8eNePgHua2LId7qs4K3R2qWxQy3Mgl23FxO+XKzaEpCP+RjRJAuN51rbrw5eq
      SbuNuOFyx6f8VWvxQK44EqqqhDMDPai+RwPZpVvEQ+kR7HTmKrfp/goetgb94DmM
      qEJmBHvKWHIJZFC+ulyriX874X0ZIU3+w+3A1YDbv17SKCnU/Oe8OJjMYJWdUEYC
      IaxWHzqbiXg5JluiEKx/gJNIJvhtry+kJMHCHR3lPAsG9EWPUzvrjpkyUXbnnv+x
      DWFInEeuncpend5dMZlXhx+BXyptRoGjkSNTAQIDAQABAoIBACOGw3Qq922gBSfB
      fHAXNDZcHY6apUDtjupJfCUhZOac5TGRp+Psi2gKpYge9XXB8FJYEU1Y2fUxLTRH
      fRYjqxG4rd+UgynWuxua1wBrmiSvR1HaMnHZ7yj987lj1bgqgyotzo2y95xM5u/s
      EcTk6IbYh4Ql1juw2zJVOcJjGiCdgdvgAcIvjSRT+sbBL4biw4BRajsX8t+xD73f
      jOfK6RhroZgRgtYMYNsG4gtPoGErYyqNdsOccr81VDpo2HEcOxk1ymy/bea6hEBd
      m3gNA/P23GUxycRcXd4Ki9GfW/XdnHDoGzLVonEJa7xz6uSuw6PhlxVH4+il7PJk
      hDzsJqECgYEA9fak4D+0G7mEKDAec052etqPcjzZsPYUWdj2SLeVD/mF6IJDW+KI
      efCxbzW53gBR91ugmwPxQ4Ti9CBpRNZlKcAPFEU7/S2Njfdc+i/QuQoZQW5Q1FHT
      M70z9WHQFdmWy0D45gndAt9l93ZRRhn32oEsY/OjS6J69ghGOT/ELJ0CgYEA6n91
      UgiBOhg0i/FubstUVbu1xn2XxRgzGpI7ZsrNfxU8jDEwZa9twbhWrUXQhWtq7eWR
      mgWfK3usCxoOiXHJFNeN0jkQxiPErNAz4CrvDbUPboqKHXmeP8f2YGVJl5t1oW7P
      DVTZaLM5Ss1PMlzqtr7DYkm84u8HBa15biWQaLUCgYEAmmWIG+iBM8IhjmSeSL1h
      LD9UOl6uPCJMphXGi+EJpix4/Xn/tIcgKoOHrgqosQ28ZizTRVuVMFATczGBQx/e
      AvY3wP6w6H2W1R4I9FfdironHmaUQKNYk6raGdebmouq183iL+zTGoGHbW6NGBcm
      +beKWPfQcqL80sJg6oD3sRUCgYEAovjAJaoJfcGSy2uYj2G6k/boBzIEB5Og+KeG
      pxLtLJQqx1fsRc9dHVQq0TODDyavYvS4c23SyFqkH/cVAUrWMCj6xI6qbLoxFtWA
      KBxOlZ0vQ2j/Qiri43rqbOYX9kixwOcM+Tvt+QkOGUGE+ACBk04S5j1PC/yJSdXd
      XcK3kT0CgYEAzle+WKkSCsQPMRcP+pWPBK4YGs/pi3fLYlNFN8dCZctLCVXIgXao
      1CzB8vsEva40zy06xHaqbNNpnH0zI0dcsnRFWUqNilZnEYDYjVb0G8oEcNY9AEXm
      P5Z/XHQfurMSM19OUK5EQrSvb7TZKcxV2m3ZBMXg7ccUjh+ZcR3X7rM=
      -----END RSA PRIVATE KEY-----
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: 7000
    syslog_config: disabled
    system_domain: local.pcfdev.io
    tcp_routes_config: enabled
    tls_config: enabled
    vmr_agent_port: 18080
  resource_pool: common-resource-pool
  templates:
  - name: docker
    release: docker
  - name: prepare_vmr
    release: solace-vmr
  - name: containers
    release: solace-vmr
  - name: vmr_agent
    release: solace-vmr
- name: deploy-all
  templates:
  - name: deploy-all
    release: solace-messaging
  instances: 1
  lifecycle: errand
  resource_pool: common-resource-pool
  networks:
  - name: test-network
  properties:
    cf:
      admin_user: admin
      admin_password: admin
    domain: 'local.pcfdev.io'
    app_domains:
    - 'local.pcfdev.io'
    org: 'solace'
    space: 'solace-messaging'
    ssl:
      skip_cert_verify: true
    security:
      user: 'solacedemo'
      password: 'solacedemo'
    starting_port: 7000
    vmr_admin_password: 'admin'
    tls_config:
      value: 'disabled'
    application_access_auth_scheme:
      value: 'vmr_internal'
    management_access_auth_scheme:
      value: 'vmr_internal'
    ldap_config:
      value: 'disabled'
    syslog_config:
      value: 'disabled'
    tcp_routes_config:
      selected_option:
        cf_credentials:
          identity: 'solace_router' 
          password: '1234'
        smf_tcp_route_enabled: 'enabled_by_default'
        smf_tls_tcp_route_enabled: 'enabled_by_default'
        smf_zip_tcp_route_enabled: 'enabled_by_default'
        web_messaging_tcp_route_enabled: 'enabled_by_default'
        web_messaging_tls_tcp_route_enabled: 'enabled_by_default'
        mqtt_tcp_route_enabled: 'enabled_by_default'
        mqtt_tls_tcp_route_enabled: 'enabled_by_default'
        mqtt_ws_tcp_route_enabled: 'enabled_by_default'
        mqtt_wss_tcp_route_enabled: 'enabled_by_default'
        rest_tcp_route_enabled: 'enabled_by_default'
        rest_tls_tcp_route_enabled: 'enabled_by_default'
      value: 'enabled'
    solace_vmr:
      shared_vmr:
        host: [10.244.0.3]
        hosts: [10.244.0.3]
      community_vmr:
        host: [10.244.0.4]
        hosts: [10.244.0.4]
    solace_messaging:
      user: solacedemo
      password: solacedemo
      enable_global_access_to_plans: true
- name: delete-all
  templates:
  - name: delete-all
    release: solace-messaging
  instances: 1
  lifecycle: errand
  resource_pool: common-resource-pool
  networks:
  - name: test-network
  properties:
    cf:
      admin_user: admin
      admin_password: admin
    domain: 'local.pcfdev.io'
    app_domains:
    - 'local.pcfdev.io'
    org: 'solace'
    space: 'solace-messaging'
    ssl:
      skip_cert_verify: true
    security:
      user: 'solacedemo'
      password: 'solacedemo'
    starting_port: 7000
    vmr_admin_password: 'admin'
    tls_config:
      value: 'disabled'
    application_access_auth_scheme:
      value: 'vmr_internal'
    management_access_auth_scheme:
      value: 'vmr_internal'
    ldap_config:
      value: 'disabled'
    syslog_config:
      value: 'disabled'
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: 'not_allowed'
      value: 'disabled'
    solace_vmr:
      shared_vmr:
        host: [10.244.0.3]
        hosts: [10.244.0.3]
      community_vmr:
        host: [10.244.0.4]
        hosts: [10.244.0.4]
    solace_messaging:
      user: solacedemo
      password: solacedemo
      enable_global_access_to_plans: true
name: solace-vmr-warden-deployment
networks:
- name: test-network
  subnets:
  - cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/28
    static:
    - 10.244.0.2
    - 10.244.0.3
    - 10.244.0.4
  - cloud_properties:
      name: random
    gateway: 10.244.0.17
    range: 10.244.0.16/28
    static: []
  type: manual
releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest
- name: solace-messaging
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 0
  canary_watch_time: 30000-240000
  max_in_flight: 3
  update_watch_time: 30000-600000
