name: {{ name }}
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest

compilation:
  workers: 1
  network: test-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
{% with static_ips = testNetwork.static_ips %}
  {% import 'test-network.yml' %}
{% endwith %}

jobs:
{% for job in vmrJobs %}
  {% with 
    name            = job.name,
    isHa            = job.isHA,
    static_ips      = job.static_ips,
    poolName        = job.poolName,
    solaceDockerFile= job.solaceDockerFile,
    usingCerts      = usingCerts
  %}
    {% import 'vmr-job.yml' %}
  {% endwith %}
{% endfor %}
- name: UpdateServiceBroker
  templates:
  -  {name: update_config, release: solace-vmr}
  persistent_disk: 4096
  instances: 1
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
    - {{ updateServiceBrokerJob.ip }}
  properties:
    vmr_agent_port: 18080
    starting_port: 7000
    broker_user: 'solacedemo'
    broker_password: 'solacedemo'
    broker_hostname: 'solace-messaging.local.pcfdev.io'
    heartbeat_rate: 15000
    admin_password: 'admin'
    admin_user: 'admin'
    support_user: 'support'
    support_password: 'support'
    semp_port: 8080
    semp_ssl_port: 943
    system_domain: 'local.pcfdev.io'
    ssh_port: 2222
    {% if usingCerts %}
      {% include 'cert.yml' %}
    {% endif %}

    {% for listName, vmrProps in updateServiceBrokerJob.vmrProps.items() %}
      {{ listName }}_vmr_instances: {{ vmrProps.numInstances }}
      {{ listName }}_vmr_list:
      {{ for ip in vmrProps.ipList }}
      - {{ ip }}
      {% endfor %}
    {% endfor %}
