name: {{ name }}
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest

compilation:
  workers: 1
  network: test-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 1

resource_pools:
- name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
{% with static_ips = testNetwork.static_ips %}
    {% include 'test-network.yml' %}
{% endwith %}


jobs:
{% for job in vmrJobs %}
    {% with 
        name             = job.name,
        numInstances     = job.numInstances,
        static_ips       = job.static_ips,
        poolName         = job.poolName,
        solaceDockerFile = job.solaceDockerFile,
        usingCerts       = usingCerts
    %}
        {% include 'vmr-job.yml' %}
    {% endwith %}

{% endfor %}

{% with 
    ip           = updateServiceBrokerJob.ip,
    vmrPropsList = updateServiceBrokerJob.vmrPropsList,
    usingCerts   = usingCerts
%}
    {% include 'update-service-broker-job.yml' %}
{% endwith %}
